services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'STORAGE_PROVIDER=s3'
      - 'S3_REGION_NAME=eu-central-003'
      - 'S3_ENDPOINT_URL=https://s3.eu-central-003.backblazeb2.com'
      - 'S3_ACCESS_KEY_ID=0039151ad4f91a3e6955d651db3414fd581100074e'
      - 'S3_SECRET_ACCESS_KEY=00367e88f76782100000000000001'
      - 'S3_BUCKET_NAME=OWUI25'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
